# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets executed

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
execDir = os.path.split(thisDir)[1]
dialogBox = RsgDialog(title='Output Node&Element', kernelModule='outputNodeElement', kernelFunction='main', includeApplyBtn=True, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=execDir)
RsgLabel(p='DialogBox', text='Generate node and element information for assembled instances', useBoldFont=True)
RsgLabel(p='DialogBox', text='Different elements with different numbers of nodes are not supported', useBoldFont=False)
RsgHorizontalFrame(name='HFrame_3', p='DialogBox', layout='0', pl=0, pr=0, pt=0, pb=0)
RsgTextField(p='HFrame_3', fieldType='String', ncols=18, labelText='Model name:', keyword='modelname', default='Model-1')
RsgTextField(p='HFrame_3', fieldType='String', ncols=18, labelText='Instancename:', keyword='instancename', default='Part-1-1')
RsgHorizontalFrame(name='HFrame_5', p='DialogBox', layout='0', pl=0, pr=0, pt=0, pb=0)
RsgHorizontalFrame(name='HFrame_2', p='HFrame_5', layout='0', pl=0, pr=0, pt=0, pb=0)
RsgCheckButton(p='HFrame_2', text='Output node', keyword='nodeY', default=True)
RsgTextField(p='HFrame_2', fieldType='String', ncols=7, labelText='Filename:', keyword='filen', default='node.txt')
RsgSeparator(p='HFrame_2')
RsgHorizontalFrame(name='HFrame_1', p='HFrame_5', layout='0', pl=0, pr=0, pt=0, pb=0)
RsgCheckButton(p='HFrame_1', text='Output elem', keyword='elementY', default=True)
RsgTextField(p='HFrame_1', fieldType='String', ncols=7, labelText='Filename:', keyword='filel', default='element.txt')
dialogBox.show()